version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  ml-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:v11.2.2
    container_name: 3p_ml-testing-toolkit
    volumes:
      - "./ml-testing-toolkit/spec_files:/opt/mojaloop-testing-toolkit/spec_files"
      - "./ml-testing-toolkit/secrets:/opt/mojaloop-testing-toolkit/secrets"
    ports:
      - "15000:5000"
      - "5050:5050"
    command: npm start
    networks:
      - mojaloop-net
    extra_hosts:
      - "inbound-thirdparty-scheme-adapter:172.17.0.1"
      - "outbound-thirdparty-scheme-adapter:172.17.0.1"
      - "ml-testing-toolkit:172.17.0.1"

  ml-testing-toolkit-ui:
    image: mojaloop/ml-testing-toolkit-ui:v11.2.0
    container_name: 3p_ml-testing-toolkit-ui
    ports:
      - "6060:6060"
    command: nginx -g "daemon off;"
    networks:
      - mojaloop-net

  mongo:
    image: mongo
    container_name: 3p_mongo
    ports:
      - "27017:27017"